### ISSUE TITLE
Add kaillera netplay support

### ISSUE THREAD

**Issue by mxsymeg** [rofl0r/gnuboy#8]
https://kaillerareborn.github.io/

Hopefully support for kaillera netplay can be added in subsequent releases!

**Comment by rofl0r** [comment]
when you posted the exact same request to desmume, i took a look at your link, just to find that the page is seriously lacking in information. basically just a high-level overview that gives a very rough idea what it is, but no details whatsoever, and no way to find out more without starting a manual research. as a developer i expect to find all required information to be able to implement the protocol, or whatever it is.
therefore i'm closing this until the relevant information is being made available.
